name: yh_design_system
description: "yhlab's design system package"
version: 2.0.0
homepage: "https://github.com/EE-Yat-Ho/yh_design_system"
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # svg -> 노출되지 않는 이미지 존재, 성능이 떨어지는 경우도 많아서 png 하기로
  # flutter_svg: 2.1.0
  
  # 국제화
  # 앱 패키지에 있는 json 파일들을 참조하게됨
  easy_localization: ^3.0.8

  # 유틸들
  yh_util:
    git:
      url: https://github.com/EE-Yat-Ho/yh_util.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
  - family: SpoqaHanSansNeo
    fonts:
      - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
        weight: 700
      - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
        weight: 500
  - family: SANGJUDajungdagam
    fonts:
      - asset: assets/fonts/SANGJUDajungdagam.otf
        weight: 400
